### ISSUE TITLE
./run --emulator gem5: Error UnboundLocalError: local variable 'arm_kernel_cli' referenced before assignment

### ISSUE THREAD

**Issue by rahulravi26081990** [cirosantilli/linux-kernel-module-cheat#158]
rahulravi26@ubuntu2004-VirtualBox:~/work/work/buildroot/linux-kernel-module-cheat$ ./run --emulator gem5
+ cat << 'EOF' > /home/rahulravi26/work/work/buildroot/linux-kernel-module-cheat/out/run/gem5/x86_64/0/readfile

EOF
Traceback (most recent call last):
  File "./run", line 1013, in <module>
    Main().cli()
  File "/home/rahulravi26/work/work/buildroot/linux-kernel-module-cheat/cli_function.py", line 267, in cli
    exit_status = self.cli_noexit(*args, **kwargs)
  File "/home/rahulravi26/work/work/buildroot/linux-kernel-module-cheat/cli_function.py", line 258, in cli_noexit
    return self._do_main(vars(args))
  File "/home/rahulravi26/work/work/buildroot/linux-kernel-module-cheat/cli_function.py", line 152, in _do_main
    return self.main(**self._get_args(kwargs))
  File "/home/rahulravi26/work/work/buildroot/linux-kernel-module-cheat/common.py", line 1540, in main
    ret = self.timed_main()
  File "./run", line 616, in timed_main
    cmd.extend(['--command-line', 'earlycon={} earlyprintk={} lpj=7999923 root=/dev/sda {}'.format(arm_kernel_cli, console, console, kernel_cli), LF])
UnboundLocalError: local variable 'arm_kernel_cli' referenced before assignment

**Note:-** I have removed the out directory and clean build gem5 for x86_64. While running gem5 for aarch64, I was taking long time but still not going to console prompt. so I thought to give a try to x86_64 gem5. But after build, unable to run.

**Comment by cirosantilli** [comment]
Thanks for this. Let me know if the patch worked.
