### ISSUE TITLE
Running gem5 using command line generated by ./run script manually fails with "IOError: Can't find a path to system files"

### ISSUE THREAD

**Issue by guoqinglei** [cirosantilli/linux-kernel-module-cheat#94]
the command line and error log is as follows:

```
tom@tom-pc:~/git/linux-kernel-module-cheat$ /home/tom/git/linux-kernel-module-cheat/out/gem5/default/build/ARM/gem5.opt --debug-file trace.txt --listener-mode on --outdir /home/tom/git/linux-kernel-module-cheat/out/run/gem5/aarch64/0/m5out /home/tom/git/linux-kernel-module-cheat/submodules/gem5/configs/example/fs.py --disk-image /home/tom/git/linux-kernel-module-cheat/out/buildroot/build/br2018.11_gcc8.3/aarch64/images/rootfs.ext2 --kernel /home/tom/git/linux-kernel-module-cheat/out/linux/default/aarch64/vmlinux --mem-size 256MB --num-cpus 1 --script /home/tom/git/linux-kernel-module-cheat/out/run/gem5/aarch64/0/readfile --machine-type VExpress_GEM5_V1 --command-line 'earlyprintk=pl011,0x1c090000 lpj=19988480 rw loglevel=8 mem=256MB root=/dev/sda console_msg_format=syslog nokaslr norandmaps panic=-1 printk.devkmsg=on printk.time=y rw console=ttyAMA0 - lkmc_home=/lkmc lkmc_eval_base64="L2RheHB5X3BhY2thZ2Uub3V0"' --param 'system.panic_on_panic = True'
gem5 Simulator System.  http://gem5.org
gem5 is copyrighted software; use the --copyright option for details.

gem5 compiled Sep  9 2019 12:51:11
gem5 started Oct 25 2019 17:16:57
gem5 executing on tom-pc, pid 8452
command line: /home/tom/git/linux-kernel-module-cheat/out/gem5/default/build/ARM/gem5.opt --debug-file trace.txt --listener-mode on --outdir /home/tom/git/linux-kernel-module-cheat/out/run/gem5/aarch64/0/m5out /home/tom/git/linux-kernel-module-cheat/submodules/gem5/configs/example/fs.py --disk-image /home/tom/git/linux-kernel-module-cheat/out/buildroot/build/br2018.11_gcc8.3/aarch64/images/rootfs.ext2 --kernel /home/tom/git/linux-kernel-module-cheat/out/linux/default/aarch64/vmlinux --mem-size 256MB --num-cpus 1 --script /home/tom/git/linux-kernel-module-cheat/out/run/gem5/aarch64/0/readfile --machine-type VExpress_GEM5_V1 --command-line 'earlyprintk=pl011,0x1c090000 lpj=19988480 rw loglevel=8 mem=256MB root=/dev/sda console_msg_format=syslog nokaslr norandmaps panic=-1 printk.devkmsg=on printk.time=y rw console=ttyAMA0 - lkmc_home=/lkmc lkmc_eval_base64="L2RheHB5X3BhY2thZ2Uub3V0"' --param 'system.panic_on_panic = True'

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/tom/git/linux-kernel-module-cheat/out/gem5/default/build/ARM/python/m5/main.py", line 438, in main
    exec(filecode, scope)
  File "/home/tom/git/linux-kernel-module-cheat/submodules/gem5/configs/example/fs.py", line 340, in <module>
    test_sys = build_test_system(np)
  File "/home/tom/git/linux-kernel-module-cheat/submodules/gem5/configs/example/fs.py", line 102, in build_test_system
    security=options.enable_security_extensions)
  File "/home/tom/git/linux-kernel-module-cheat/submodules/gem5/configs/common/FSConfig.py", line 251, in makeArmSystem
    self.cf0.childImage(mdesc.disk())
  File "/home/tom/git/linux-kernel-module-cheat/submodules/gem5/configs/common/Benchmarks.py", line 59, in disk
    return disk(self.diskname)
  File "/home/tom/git/linux-kernel-module-cheat/submodules/gem5/configs/common/SysPaths.py", line 62, in __call__
    raise IOError("Can't find a path to system files.")
IOError: Can't find a path to system files.
```

I have run the script: ./run --buildroot-build-id br2018.11_gcc8.3 --eval-after '/daxpy_package.out', the gem5 run is ok.
But why IOError happens here if I try the generated command line by previous script ?

**Comment by cirosantilli** [comment]
When you do`./run`, the generated output contains starts with:

```
+ M5_PATH=/path/to/linux-kernel-module-cheat/out/gem5/master/system \    
  M5_OVERRIDE_PY_SOURCE=true \                                        
  /path/to/linux-kernel-module-cheat/out/gem5/master/build/ARM/gem5.opt \
```

so there are those two environment variables that you are not exporting in your command, and the lack of `M5_PATH` is the responsible for the error as mentioned at: https://stackoverflow.com/questions/56319473/gem-5-ioerror-cant-find-a-path-to-system-files-full-system-x86-simulation-set

**Comment by guoqinglei** [comment]
> When you do`./run`, the generated output command starts with:
> 
> ```
> + M5_PATH=/path/to/linux-kernel-module-cheat/out/gem5/master/system \    
>   M5_OVERRIDE_PY_SOURCE=true \                                        
>   /path/to/linux-kernel-module-cheat/out/gem5/master/build/ARM/gem5.opt \
> ```
> 
> so there are those two environment variables that you are not exporting in your command, and the lack of `M5_PATH` is the responsible for the error as mentioned at: https://stackoverflow.com/questions/56319473/gem-5-ioerror-cant-find-a-path-to-system-files-full-system-x86-simulation-set

Thanks a lot. I have exported the above environmental variable you mentioned, and it works.

**Comment by cirosantilli** [comment]
Great! Closing as resolved in that case.
