### ISSUE TITLE
does not build on ubuntu 19.10

### ISSUE THREAD

**Issue by RobertHenry6bev** [cirosantilli/linux-kernel-module-cheat#95]
On a ubuntu 19.10 system, I checkout and do the basic thing. It fails.  It is conceivable that my apt package system is somehow messed up.

./build --download-dependencies qemu-buildroot

....
gets error:

+ sudo apt-get build-dep \
  qemu \
;
Reading package lists... Done
E: You must put some 'source' URIs in your sources.list
Traceback (most recent call last):
  File "./build", line 548, in <module>
    Main().cli()
  File "/mnt/robhenry/cirosantilli/linux-kernel-module-cheat/cli_function.py", line 245, in cli
    exit_status = self.cli_noexit(*args, **kwargs)
  File "/mnt/robhenry/cirosantilli/linux-kernel-module-cheat/cli_function.py", line 236, in cli_noexit
    return self._do_main(vars(args))
  File "/mnt/robhenry/cirosantilli/linux-kernel-module-cheat/cli_function.py", line 140, in _do_main
    return self.main(**self._get_args(kwargs))
  File "/mnt/robhenry/cirosantilli/linux-kernel-module-cheat/common.py", line 893, in main
    ret = self.timed_main()
  File "./build", line 485, in timed_main
    self.sh.add_newlines(sorted(apt_build_deps))
  File "/mnt/robhenry/cirosantilli/linux-kernel-module-cheat/shell_helpers.py", line 248, in run_cmd
    raise Exception('Command exited with status: {}'.format(returncode))
Exception: Command exited with status: 100
robhenry@robhenry-desk-01:/mnt/robhenry/cirosantilli/linux-kernel-module-cheat$

**Comment by cirosantilli** [comment]
Hi Robert,

See https://cirosantilli.com/linux-kernel-module-cheat/#put-source-uris-in-sources at cb6ea177715a43aeaa8314b4e7109535417d2315
